### ISSUE TITLE
Not recognised in extensions

### ISSUE THREAD

**Issue by VPadmin2021** [Flerex/linkedaccounts#32]
I'm in Extensions Manager after following instructions to download.
Can't find Linked Accounts.

I'm using phpBB 3.3.4
I installed the linkedaccounts folder into /ext on my site. 

It's not doing anything

**Comment by Flerex** [comment]
Did you install it with the `flerex/` folder containing the `linkedaccounts/` folder, so that it ends up in the following path `ext/flerex/linkedaccounts`?

Right now I'm not aware that there is any kind of bug regarding this. The version available in the Extension DB is working.

**Comment by VPadmin2021** [comment]
It turned out I had downloaded the Source Code version and it didn't come with flerex folder. 
I downloaded the recent one, uploaded it under flerex folder now and it's working.

I am an idiot. Thank you for your swift assistance!

**Comment by Flerex** [comment]
I don't recommend downloading directly from the source code, because there might be breaking changes. You can always download the complete bundle from either the [Extensions DB](https://www.phpbb.com/customise/db/extension/linked_accounts) or the [releases page](https://github.com/Flerex/linkedaccounts/releases).
